version: "3.8"

services:
  gitleaks:
    image: zricethezav/gitleaks:latest
    container_name: gitleaks
    volumes:
      - .:/path # Mount current directory to /path inside the container
      - ./reports/gitleaks:/gitleaks # Save the report in the ./reports/gitleaks folder
    entrypoint: ["/bin/sh", "-c"] # We will run the full command through the shell in the pipeline
    restart: unless-stopped

  dependency-check:
    image: owasp/dependency-check:latest
    container_name: dependency-check
    volumes:
      - .:/src
      - ./reports/dependency-check:/reports
    restart: unless-stopped

  owasp-zap:
    image: zaproxy/zap-stable
    container_name: owasp-zap
    ports:
      - "8080:8080"
    volumes:
      - ./reports/zap:/zap/reports
    restart: unless-stopped

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:13
    container_name: sonarqube_db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube
    volumes:
      - sonarqube_db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  sonarqube_db_data:
