apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_USERNAME: YWRtaW4=        # 'admin' encodé en base64
  DB_PASSWORD: YWRtaW4=        # 'admin' encodé en base64
  DB_DATABASE: ZGV2b3BzX2FwcA==  # 'devops_app' encodé en base64
  DB_HOST: cG9zdGdyZXM=        # 'postgres' encodé en base64
  DB_PORT: NTQzMg==            # '5432' encodé en base64
