apiVersion: v1
kind: Service
metadata:
  name: laravel-service
spec:
  selector:
    app: laravel
    version: green  # Pointe initialement vers la version Blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
